services:
  opencode:
    build:
      context: .
      args:
        TZ: ${TZ}
    image: successage/opencode-kanban
    container_name: opencode-vibe
    ports:
      - "2046:2046"
      - "3927:3927"
      - "2027:2027"
      - "2211:2211"
    volumes:
      - ./project:/home/user/project
      - ./vibe-kanban:/var/tmp/vibe-kanban
      - ./app:/app
      - ./userdata/.opencode:/home/user/.opencode-data
      - ./userdata/.config/opencode:/home/user/.config/opencode
      - ./userdata/.config/openspec:/home/user/.config/openspec
      - ./userdata/.config/vibe-kanban:/home/user/.local/share/vibe-kanban
      - ./userdata/.vibe-kanban:/home/user/.vibe-kanban
      - ./userdata/.local/share/opencode:/home/user/.local/share/opencode
      - ./userdata/.claude.json:/home/user/.claude.json
      - ./userdata/.claude:/home/user/.claude
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - OPENCODE_SERVER_PASSWORD=${OPENCODE_SERVER_PASSWORD}
      - SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
