services:
  opencode:
    image: successage/opencode-kanban
    container_name: opencode-vibe
    ports:
      - "2046:2046"
      - "3927:3927"
      - "2027:2027"
      - "2211:2211"
    volumes:
      - ./project:/root/project
      - ./vibe-kanban:/var/tmp/vibe-kanban
      - ./app:/app
      - ./userdata/.opencode:/root/.opencode
      - ./userdata/.config/opencode:/root/.config/opencode
      - ./userdata/.config/openspec:/root/.config/openspec
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
